/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: chuckevil1984 (https://sketchfab.com/chuckevil1984)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vendetta-mask-set-c00ce3a188bb4e31838534ce4fee0038
title: Vendetta-mask-set
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mask({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Mask.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.18, 0.01, 0]} rotation={[1.69, 0, -0.08]} scale={1.41}>
          <mesh geometry={nodes.Plane003_0.geometry} material={nodes.Plane003_0.material} />
        </group>
        <group position={[-5.23, -1.24, -4.21]} rotation={[1.75, 0.44, 0.42]} scale={0.59}>
          <mesh geometry={nodes.Plane005_0.geometry} material={nodes.Plane005_0.material} />
        </group>
        <group position={[5.86, -3.06, -3.34]} rotation={[1.26, 0, 0.17]} scale={0.8}>
          <mesh geometry={nodes.Plane006_0.geometry} material={nodes.Plane006_0.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Mask.gltf')
